### ISSUE TITLE
repeat region size

### ISSUE THREAD

**Issue by ytguojian** [bvalot/panISa#1]
Hi,
I am using this package to detect IS in genome. What I want to ask is can we set the minimum size of direct repeat region? Because I have noticed that there are some single size repeat region in the result, however, in my opinion, the size larger than 1 or 2 would be more accurate. How do you think?
Is that the option -p in this meaning?

And also, how can we determine the hetero or homo genotypes of the IS site? Just according to the count of End clipped reads and Start clipped reads to determine which is hetero- and homo- , Right?

Cheers,
Jian

**Comment by bvalot** [comment]
Hi,

We only can set the maximum size of direct repeat  using the -s option, not the minimum one. The -p option is use to construct the DR, IRL and IRR region using reads. For each nucleotide, if the percentage of reads with the same base is superior to the threshold, the base is report. Otherwise, a N is report.

For the hetero/homo genotype, you can use the number of clipped reads. I must precise you, that the program have been preliminary developed to detect IS in bacteria, not in eukaryote.  I have no idea how the program works with this type of data.

Cheers,
Benoit

**Comment by ytguojian** [comment]
Hi Benoit,
Thanks for your reply. I have written a perl script to filter the DR size according to the result and already finished the genotype based on the clipped reads. And, according to my study,  I think this program is also suit for eukaryote. Thanks a lot!

Cheers,
Jian
