### ISSUE TITLE
Is it different from ISmapper?

### ISSUE THREAD

**Issue by Isoris** [bvalot/panISa#5]
Hi,

I may not understand everyting but I am curious about in what this tool is different from ISmapper?
Why develop a tool that already exists?

Thank you for your answer

**Comment by bvalot** [comment]
You can look at the [paper on bioinformatics](https://academic.oup.com/bioinformatics/article/34/22/3795/5040324?login=false).

In short, ISMapper as like RetroSeq identify the insertion of TEs based on a query TE database as input, preventing the detection of unknown elements (Hawkey et al., 2015; Keane et al., 2013).
In comparison, panISa use the pattern of read alignment due to direct repeat to detect potentiel IS insertion.

**Comment by Isoris** [comment]
Thank you for the answer.
